name: build
on:
  pull_request_target:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - edited
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: "echo hello world"